MyExplore/Controllers/MyExploreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyExplore.Controllers
{
    public class MyExploreController : Controller
    {
        // GET: MyExplore
        public ActionResult Intro()
        {
            return View();
        }
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Hotel()
        {
            return View();
        }
        public ActionResult Vacations()
        {
            return View();
        }
        public ActionResult ThingsToDo()
        {
            return View();
        }
        public ActionResult MyAccount()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult PlanTrip()
        {
            return View();
        }
        public ActionResult Details()
        {
            return View();
        }
    }
}

MyExplore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MyExplore/Views/Shared/_LayoutMyExplore.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="~/Content/Explore/dist/css/bootstrap.css" rel="stylesheet" media="screen">
    <link href="~/Content/Explore/assets/css/custom.css" rel="stylesheet" media="screen">
    <link href="~/Content/Explore/examples/carousel/carousel.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400,300,300italic' rel='stylesheet' type='text/css'>
    <!-- Font-Awesome -->
    <link rel="stylesheet" type="text/css" href="~/Content/Explore/assets/css/font-awesome.css" media="screen" />
    <!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="assets/css/font-awesome-ie7.css" media="screen" /><![endif]-->
    <!-- REVOLUTION BANNER CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="~/Content/Explore/css/fullscreen.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/Content/Explore/rs-plugin/css/settings.css" media="screen" />
    <!-- Picker -->
    <link rel="stylesheet" href="~/Content/Explore/assets/css/jquery-ui.css" />

    <!-- bin/jquery.slider.min.css -->
    <link rel="stylesheet" href="~/Content/Explore/plugins/jslider/css/jslider.css" type="text/css">
    <link rel="stylesheet" href="~/Content/Explore/plugins/jslider/css/jslider.round.css" type="text/css">

    <!-- jQuery -->
    <script src="~/Content/Explore/assets/js/jquery.v2.0.3.js"></script>
    <!-- bin/jquery.slider.min.js -->
    <script type="text/javascript" src="~/Content/Explore/plugins/jslider/js/jshashtable-2.1_src.js"></script>
    <script type="text/javascript" src="~/Content/Explore/plugins/jslider/js/jquery.numberformatter-1.2.3.js"></script>
    <script type="text/javascript" src="~/Content/Explore/plugins/jslider/js/tmpl.js"></script>
    <script type="text/javascript" src="~/Content/Explore/plugins/jslider/js/jquery.dependClass-0.1.js"></script>
    <script type="text/javascript" src="~/Content/Explore/plugins/jslider/js/draggable-0.1.js"></script>
    <script type="text/javascript" src="~/Content/Explore/plugins/jslider/js/jquery.slider.js"></script>
    <!-- end -->
</head>
<body id="top" class="thebg">

    <!-- Top wrapper -->
    <div class="navbar-wrapper2 navbar-fixed-top">
        <div class="container">
            <div class="navbar mtnav">
                <div class="container">
                    <!-- Navigation-->
                    <div class="navbar-header">
                        <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="@Url.Action("Intro","MyExplore")" class="navbar-brand"><img src="~/Content/Explore/images/logo.png" alt="Travel Agency Logo" class="logo" /></a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="@Url.Action("Home")">Home</a></li>
                            <li><a href="@Url.Action("PlanTrip")">Plan Trip</a></li>
                            <li><a href="@Url.Action("Hotel")">Hotels</a></li>
                            <li><a href="@Url.Action("Vacations")">Vacations</a></li>
                            <li><a href="@Url.Action("ThingsToDo")">Things To Do</a></li>
                            <li class="dropdown">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="@Url.Action("Login")">My Account<b class="lightcaret mt-2"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Login")">Login</a></li>
                                    <li><a href="@Url.Action("Register")">Register</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- /Navigation-->
                </div>

            </div>
        </div>
    </div>
    <!-- /Top wrapper -->

    @RenderBody()
    @RenderSection("scripts", required: false)
</body>
</html>